### ISSUE TITLE
GM_config: get called before init

### ISSUE THREAD

**Issue by javsanpar** [tadwohlrapp/soldby#21]
### Problem description

Hi!

I believe soldby has been affected by the following breaking change in GM_config: https://github.com/sizzlemctwizzle/GM_config/issues/113.

Thank you for creating soldby!

### SoldBy Version

1.7.0

### Browser

Firefox

### Userscript manager

Violentmonkey

**Comment by Martii** [comment]
Skim notes:

Does have:

https://github.com/tadwohlrapp/soldby/blob/783da9d73d898f36e35cce02dff13318c18dddf2/userscript/soldby.user.js#L124-L126

Additional code early launch points outside of this at *(the `get` requests before `init` Ref: [these](https://github.com/tadwohlrapp/soldby/blob/783da9d73d898f36e35cce02dff13318c18dddf2/userscript/soldby.user.js#L173-L174) and [this](https://github.com/tadwohlrapp/soldby/blob/783da9d73d898f36e35cce02dff13318c18dddf2/userscript/soldby.user.js#L176))*:

https://github.com/tadwohlrapp/soldby/blob/783da9d73d898f36e35cce02dff13318c18dddf2/userscript/soldby.user.js#L157-L177

... and possibly this *(not fully traced)*...

https://github.com/tadwohlrapp/soldby/blob/783da9d73d898f36e35cce02dff13318c18dddf2/userscript/soldby.user.js#L221-L236


Most of the functions should be able to remain unindented/changed since they are probably called from the existing code launch points.

Thanks for the look and I hope this gets you kick-started for the migration mentioned by the reporter for GM_config *(GMC as I call it)*.

**Comment by tadwohlrapp** [comment]
Hey @javsanpar and @Martii, thank you for reporting in and investigating the issue!

I personally try to avoid browsing Amazon as much as possible, so I didn't even notice SoldBy breaking. Also I probably should enable GitHub's notifications. Sorry for the delay!

The issue will be fixed in the coming days.

Also, if you want to help / contribute feel free to open pull requests anytime ;)
